# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Function App - my-function-app-2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Adjust if you need a different version

      - name: Install Node.js dependencies
        run: npm install

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89BE8B368C69410ABCBDFF9E7350C4BD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_28A1EBE9461D4861AA7B381BE406A16C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_374A9109B923470AA205E494D596EAA2 }}

      - name: Run Azure Functions Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: 'my-function-app-2025'
          slot-name: 'Production'
          package: '.'
          
